<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HistoricalFact;

class HistoricalCalendarSeeder extends Seeder
{
    public function run(): void
    {
        $events = [

            // ===== ВЕЛИКАЯ ОТЕЧЕСТВЕННАЯ =====
            [
                'content' => 'Началась Великая Отечественная война.',
                'event_day' => 22,
                'event_month' => 6,
                'event_year' => 1941,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 10,
            ],
            [
                'content' => 'Победа в Великой Отечественной войне.',
                'event_day' => 9,
                'event_month' => 5,
                'event_year' => 1945,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 10,
            ],
            [
                'content' => 'Началась Сталинградская битва.',
                'event_day' => 17,
                'event_month' => 7,
                'event_year' => 1942,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 9,
            ],
            [
                'content' => 'Полностью снята блокада Ленинграда.',
                'event_day' => 27,
                'event_month' => 1,
                'event_year' => 1944,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 9,
            ],

            // ===== РЕФОРМЫ И ГОСУДАРСТВО =====
            [
                'content' => 'Отмена крепостного права в Российской империи.',
                'event_day' => 19,
                'event_month' => 2,
                'event_year' => 1861,
                'type' => 'reform',
                'country' => 'Россия',
                'priority' => 9,
            ],
            [
                'content' => 'Проведена первая всероссийская перепись населения.',
                'event_day' => 28,
                'event_month' => 1,
                'event_year' => 1897,
                'type' => 'reform',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Принята Конституция Российской Федерации.',
                'event_day' => 12,
                'event_month' => 12,
                'event_year' => 1993,
                'type' => 'reform',
                'country' => 'Россия',
                'priority' => 8,
            ],

            // ===== КУЛЬТУРА =====
            [
                'content' => 'Родился Александр Сергеевич Пушкин.',
                'event_day' => 6,
                'event_month' => 6,
                'event_year' => 1799,
                'type' => 'culture',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'Родился Лев Николаевич Толстой.',
                'event_day' => 9,
                'event_month' => 9,
                'event_year' => 1828,
                'type' => 'culture',
                'country' => 'Россия',
                'priority' => 7,
            ],

            // ===== НАУКА =====
            [
                'content' => 'Юрий Гагарин совершил первый полёт человека в космос.',
                'event_day' => 12,
                'event_month' => 4,
                'event_year' => 1961,
                'type' => 'science',
                'country' => 'СССР',
                'priority' => 10,
            ],

            // ===== РЕЛИГИЯ =====
            [
                'content' => 'Крещение Руси князем Владимиром.',
                'event_day' => 28,
                'event_month' => 7,
                'event_year' => 988,
                'type' => 'religion',
                'country' => 'Русь',
                'priority' => 8,
            ],

            // ===== ВЕЛИКАЯ ОТЕЧЕСТВЕННАЯ =====
            [
                'content' => 'Началась Курская битва.',
                'event_day' => 5,
                'event_month' => 7,
                'event_year' => 1943,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 9,
            ],
            [
                'content' => 'Завершилась Сталинградская битва.',
                'event_day' => 2,
                'event_month' => 2,
                'event_year' => 1943,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 9,
            ],
            [
                'content' => 'Освобождение Киева от немецко-фашистских войск.',
                'event_day' => 6,
                'event_month' => 11,
                'event_year' => 1943,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 8,
            ],
            [
                'content' => 'Началась оборона Москвы.',
                'event_day' => 30,
                'event_month' => 9,
                'event_year' => 1941,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 9,
            ],
            [
                'content' => 'Советские войска вошли в Берлин.',
                'event_day' => 25,
                'event_month' => 4,
                'event_year' => 1945,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 9,
            ],

// ===== РОССИЙСКАЯ ИМПЕРИЯ =====
            [
                'content' => 'Началось правление Петра I.',
                'event_day' => 7,
                'event_month' => 5,
                'event_year' => 1682,
                'type' => 'reform',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Учреждён Санкт-Петербург.',
                'event_day' => 27,
                'event_month' => 5,
                'event_year' => 1703,
                'type' => 'reform',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Бородинское сражение.',
                'event_day' => 7,
                'event_month' => 9,
                'event_year' => 1812,
                'type' => 'war',
                'country' => 'Россия',
                'priority' => 9,
            ],

// ===== СССР =====
            [
                'content' => 'Образован Союз Советских Социалистических Республик.',
                'event_day' => 30,
                'event_month' => 12,
                'event_year' => 1922,
                'type' => 'reform',
                'country' => 'СССР',
                'priority' => 9,
            ],
            [
                'content' => 'Запуск первого искусственного спутника Земли.',
                'event_day' => 4,
                'event_month' => 10,
                'event_year' => 1957,
                'type' => 'science',
                'country' => 'СССР',
                'priority' => 9,
            ],

// ===== КУЛЬТУРА =====
            [
                'content' => 'Родился Фёдор Михайлович Достоевский.',
                'event_day' => 11,
                'event_month' => 11,
                'event_year' => 1821,
                'type' => 'culture',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'Родился Антон Павлович Чехов.',
                'event_day' => 29,
                'event_month' => 1,
                'event_year' => 1860,
                'type' => 'culture',
                'country' => 'Россия',
                'priority' => 7,
            ],

// ===== СЕМЕЙНЫЕ СОБЫТИЯ =====
            [
                'content' => 'Международный день семьи.',
                'event_day' => 15,
                'event_month' => 5,
                'event_year' => null,
                'type' => 'family',
                'country' => 'Мир',
                'priority' => 6,
            ],
            [
                'content' => 'День матери в России.',
                'event_day' => 26,
                'event_month' => 11,
                'event_year' => null,
                'type' => 'family',
                'country' => 'Россия',
                'priority' => 6,
            ],
// ===== ДОПОЛНИТЕЛЬНЫЕ СОБЫТИЯ РОССИИ =====
            [
                'content' => 'Манифест об учреждении Государственной думы.',
                'event_day' => 6,
                'event_month' => 8,
                'event_year' => 1905,
                'type' => 'reform',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'Февральская революция в России.',
                'event_day' => 23,
                'event_month' => 2,
                'event_year' => 1917,
                'type' => 'reform',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Октябрьская революция.',
                'event_day' => 7,
                'event_month' => 11,
                'event_year' => 1917,
                'type' => 'reform',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Началась Первая мировая война для России.',
                'event_day' => 1,
                'event_month' => 8,
                'event_year' => 1914,
                'type' => 'war',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Подписан Брест-Литовский мир.',
                'event_day' => 3,
                'event_month' => 3,
                'event_year' => 1918,
                'type' => 'war',
                'country' => 'Россия',
                'priority' => 7,
            ],

// ===== НАУКА И ПРОМЫШЛЕННОСТЬ =====
            [
                'content' => 'Открытие Московского университета.',
                'event_day' => 25,
                'event_month' => 1,
                'event_year' => 1755,
                'type' => 'science',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'Создание Академии наук.',
                'event_day' => 8,
                'event_month' => 2,
                'event_year' => 1724,
                'type' => 'science',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'Первая электростанция в России начала работу.',
                'event_day' => 4,
                'event_month' => 7,
                'event_year' => 1886,
                'type' => 'science',
                'country' => 'Россия',
                'priority' => 6,
            ],

// ===== КУЛЬТУРА =====
            [
                'content' => 'Открытие Большого театра в Москве.',
                'event_day' => 20,
                'event_month' => 10,
                'event_year' => 1856,
                'type' => 'culture',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'Основание Третьяковской галереи.',
                'event_day' => 22,
                'event_month' => 5,
                'event_year' => 1856,
                'type' => 'culture',
                'country' => 'Россия',
                'priority' => 6,
            ],
            [
                'content' => 'Основание Эрмитажа.',
                'event_day' => 7,
                'event_month' => 12,
                'event_year' => 1764,
                'type' => 'culture',
                'country' => 'Россия',
                'priority' => 6,
            ],

// ===== ВОЕННЫЕ СОБЫТИЯ ДО ХХ ВЕКА =====
            [
                'content' => 'Ледовое побоище на Чудском озере.',
                'event_day' => 5,
                'event_month' => 4,
                'event_year' => 1242,
                'type' => 'war',
                'country' => 'Русь',
                'priority' => 8,
            ],
            [
                'content' => 'Куликовская битва.',
                'event_day' => 8,
                'event_month' => 9,
                'event_year' => 1380,
                'type' => 'war',
                'country' => 'Русь',
                'priority' => 8,
            ],
            [
                'content' => 'Полтавская битва.',
                'event_day' => 27,
                'event_month' => 6,
                'event_year' => 1709,
                'type' => 'war',
                'country' => 'Россия',
                'priority' => 8,
            ],

// ===== ПРАЗДНИКИ И СОЦИАЛЬНЫЕ ДАТЫ =====
            [
                'content' => 'День защитника Отечества.',
                'event_day' => 23,
                'event_month' => 2,
                'event_year' => null,
                'type' => 'family',
                'country' => 'Россия',
                'priority' => 6,
            ],
            [
                'content' => 'Международный женский день.',
                'event_day' => 8,
                'event_month' => 3,
                'event_year' => null,
                'type' => 'family',
                'country' => 'Мир',
                'priority' => 6,
            ],
            [
                'content' => 'День народного единства.',
                'event_day' => 4,
                'event_month' => 11,
                'event_year' => null,
                'type' => 'family',
                'country' => 'Россия',
                'priority' => 6,
            ],

// ===== ДОПОЛНИТЕЛЬНАЯ ВОВ =====
            [
                'content' => 'Началась битва за Кавказ.',
                'event_day' => 25,
                'event_month' => 7,
                'event_year' => 1942,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 8,
            ],
            [
                'content' => 'Освобождение Минска.',
                'event_day' => 3,
                'event_month' => 7,
                'event_year' => 1944,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 8,
            ],
            [
                'content' => 'Начало Берлинской операции.',
                'event_day' => 16,
                'event_month' => 4,
                'event_year' => 1945,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 9,
            ],
            [
                'content' => 'Освобождение Севастополя.',
                'event_day' => 9,
                'event_month' => 5,
                'event_year' => 1944,
                'type' => 'war',
                'country' => 'СССР',
                'priority' => 8,
            ],

// ===== РОССИЙСКАЯ ИСТОРИЯ =====
            [
                'content' => 'Восстание декабристов.',
                'event_day' => 26,
                'event_month' => 12,
                'event_year' => 1825,
                'type' => 'reform',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'Принят Судебник Ивана III.',
                'event_day' => 29,
                'event_month' => 9,
                'event_year' => 1497,
                'type' => 'reform',
                'country' => 'Русь',
                'priority' => 6,
            ],
            [
                'content' => 'Освобождение Москвы от польских интервентов.',
                'event_day' => 4,
                'event_month' => 11,
                'event_year' => 1612,
                'type' => 'war',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Основание Владивостока.',
                'event_day' => 2,
                'event_month' => 7,
                'event_year' => 1860,
                'type' => 'reform',
                'country' => 'Россия',
                'priority' => 6,
            ],

// ===== НАУКА И ТЕХНИКА =====
            [
                'content' => 'Создание первого российского паровоза.',
                'event_day' => 15,
                'event_month' => 8,
                'event_year' => 1834,
                'type' => 'science',
                'country' => 'Россия',
                'priority' => 6,
            ],
            [
                'content' => 'Открытие периодического закона Менделеевым.',
                'event_day' => 1,
                'event_month' => 3,
                'event_year' => 1869,
                'type' => 'science',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Первая атомная электростанция в мире запущена в СССР.',
                'event_day' => 27,
                'event_month' => 6,
                'event_year' => 1954,
                'type' => 'science',
                'country' => 'СССР',
                'priority' => 8,
            ],

// ===== КУЛЬТУРА =====
            [
                'content' => 'Открытие Московского художественного театра.',
                'event_day' => 14,
                'event_month' => 10,
                'event_year' => 1898,
                'type' => 'culture',
                'country' => 'Россия',
                'priority' => 6,
            ],
            [
                'content' => 'Премьера балета "Лебединое озеро".',
                'event_day' => 20,
                'event_month' => 2,
                'event_year' => 1877,
                'type' => 'culture',
                'country' => 'Россия',
                'priority' => 6,
            ],
            [
                'content' => 'Открытие Русского музея в Санкт-Петербурге.',
                'event_day' => 19,
                'event_month' => 3,
                'event_year' => 1898,
                'type' => 'culture',
                'country' => 'Россия',
                'priority' => 6,
            ],

// ===== СЕМЕЙНЫЕ И СОЦИАЛЬНЫЕ ДАТЫ =====
            [
                'content' => 'День семьи, любви и верности.',
                'event_day' => 8,
                'event_month' => 7,
                'event_year' => null,
                'type' => 'family',
                'country' => 'Россия',
                'priority' => 6,
            ],
            [
                'content' => 'Международный день пожилых людей.',
                'event_day' => 1,
                'event_month' => 10,
                'event_year' => null,
                'type' => 'family',
                'country' => 'Мир',
                'priority' => 5,
            ],
            [
                'content' => 'Международный день защиты детей.',
                'event_day' => 1,
                'event_month' => 6,
                'event_year' => null,
                'type' => 'family',
                'country' => 'Мир',
                'priority' => 5,
            ],

            // ===== ИСТОРИЯ РОДА И СЕМЬИ =====
            [
                'content' => 'В Российской империи введены метрические книги для записи рождений, браков и смертей.',
                'event_day' => 18,
                'event_month' => 12,
                'event_year' => 1722,
                'type' => 'family',
                'country' => 'Россия',
                'priority' => 9,
            ],
            [
                'content' => 'В СССР введена обязательная регистрация актов гражданского состояния (ЗАГС).',
                'event_day' => 18,
                'event_month' => 12,
                'event_year' => 1917,
                'type' => 'family',
                'country' => 'СССР',
                'priority' => 9,
            ],
            [
                'content' => 'Проведена первая всеобщая перепись населения Российской империи.',
                'event_day' => 28,
                'event_month' => 1,
                'event_year' => 1897,
                'type' => 'family',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Утверждены правила ведения домовых книг в Российской империи.',
                'event_day' => 3,
                'event_month' => 6,
                'event_year' => 1863,
                'type' => 'family',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'В России введены внутренние паспорта для учёта населения.',
                'event_day' => 27,
                'event_month' => 12,
                'event_year' => 1932,
                'type' => 'family',
                'country' => 'СССР',
                'priority' => 8,
            ],
            [
                'content' => 'Учреждён День семьи, любви и верности в России.',
                'event_day' => 8,
                'event_month' => 7,
                'event_year' => 2008,
                'type' => 'family',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'В России введена обязательная регистрация браков в государственных органах.',
                'event_day' => 19,
                'event_month' => 12,
                'event_year' => 1917,
                'type' => 'family',
                'country' => 'СССР',
                'priority' => 8,
            ],
            [
                'content' => 'Введены трудовые книжки как документ трудовой биографии человека.',
                'event_day' => 20,
                'event_month' => 12,
                'event_year' => 1938,
                'type' => 'family',
                'country' => 'СССР',
                'priority' => 7,
            ],
            [
                'content' => 'Утверждён закон о защите материнства и детства в СССР.',
                'event_day' => 27,
                'event_month' => 6,
                'event_year' => 1936,
                'type' => 'family',
                'country' => 'СССР',
                'priority' => 7,
            ],
            [
                'content' => 'Созданы первые архивы актов гражданского состояния в России.',
                'event_day' => 1,
                'event_month' => 1,
                'event_year' => 1918,
                'type' => 'family',
                'country' => 'СССР',
                'priority' => 7,
            ],
            [
                'content' => 'Введены фамилии как обязательная часть официальных документов в России.',
                'event_day' => 1,
                'event_month' => 9,
                'event_year' => 1700,
                'type' => 'family',
                'country' => 'Россия',
                'priority' => 6,
            ],
            [
                'content' => 'Начато централизованное архивное хранение метрических книг.',
                'event_day' => 14,
                'event_month' => 3,
                'event_year' => 1920,
                'type' => 'family',
                'country' => 'СССР',
                'priority' => 7,
            ],
            [
                'content' => 'Учреждён Международный день архивов.',
                'event_day' => 9,
                'event_month' => 6,
                'event_year' => null,
                'type' => 'family',
                'country' => 'Мир',
                'priority' => 6,
            ],
            [
                'content' => 'В Российской империи начали систематически вести исповедные росписи.',
                'event_day' => 1,
                'event_month' => 1,
                'event_year' => 1737,
                'type' => 'family',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'В СССР введены единые формы свидетельств о рождении.',
                'event_day' => 5,
                'event_month' => 1,
                'event_year' => 1944,
                'type' => 'family',
                'country' => 'СССР',
                'priority' => 7,
            ],

// ===== ГЕНЕАЛОГИЯ И ДОКУМЕНТЫ =====

            [
                'content' => 'В Российской империи официально закреплена практика ведения ревизских сказок.',
                'event_day' => 26,
                'event_month' => 8,
                'event_year' => 1719,
                'type' => 'genealogy',
                'country' => 'Россия',
                'priority' => 9,
            ],
            [
                'content' => 'Проведена Первая ревизия податного населения.',
                'event_day' => 1,
                'event_month' => 9,
                'event_year' => 1719,
                'type' => 'genealogy',
                'country' => 'Россия',
                'priority' => 9,
            ],
            [
                'content' => 'Проведена Десятая ревизия населения Российской империи.',
                'event_day' => 1,
                'event_month' => 1,
                'event_year' => 1858,
                'type' => 'genealogy',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Созданы первые централизованные губернские архивы.',
                'event_day' => 12,
                'event_month' => 3,
                'event_year' => 1775,
                'type' => 'genealogy',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Утверждены правила ведения метрических книг в православных приходах.',
                'event_day' => 17,
                'event_month' => 2,
                'event_year' => 1838,
                'type' => 'genealogy',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Начато централизованное хранение архивов актов гражданского состояния.',
                'event_day' => 3,
                'event_month' => 4,
                'event_year' => 1918,
                'type' => 'genealogy',
                'country' => 'СССР',
                'priority' => 9,
            ],
            [
                'content' => 'Учреждён Российский государственный исторический архив.',
                'event_day' => 11,
                'event_month' => 1,
                'event_year' => 1925,
                'type' => 'genealogy',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'Учреждён Государственный архив Российской Федерации.',
                'event_day' => 28,
                'event_month' => 4,
                'event_year' => 1992,
                'type' => 'genealogy',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'Введены единые формы архивных описей в СССР.',
                'event_day' => 15,
                'event_month' => 7,
                'event_year' => 1934,
                'type' => 'genealogy',
                'country' => 'СССР',
                'priority' => 6,
            ],
            [
                'content' => 'Принят закон об архивном деле в Российской Федерации.',
                'event_day' => 22,
                'event_month' => 10,
                'event_year' => 2004,
                'type' => 'genealogy',
                'country' => 'Россия',
                'priority' => 8,
            ],
            [
                'content' => 'Создана первая генеалогическая служба в России.',
                'event_day' => 14,
                'event_month' => 5,
                'event_year' => 1868,
                'type' => 'genealogy',
                'country' => 'Россия',
                'priority' => 6,
            ],
            [
                'content' => 'Учреждён Международный день генеалогии.',
                'event_day' => 23,
                'event_month' => 3,
                'event_year' => null,
                'type' => 'genealogy',
                'country' => 'Мир',
                'priority' => 6,
            ],
            [
                'content' => 'Опубликованы первые родословные книги дворянства.',
                'event_day' => 2,
                'event_month' => 6,
                'event_year' => 1785,
                'type' => 'genealogy',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'В России утверждены правила хранения церковных архивов.',
                'event_day' => 9,
                'event_month' => 2,
                'event_year' => 1841,
                'type' => 'genealogy',
                'country' => 'Россия',
                'priority' => 7,
            ],
            [
                'content' => 'В СССР создана система государственных архивов.',
                'event_day' => 1,
                'event_month' => 6,
                'event_year' => 1920,
                'type' => 'genealogy',
                'country' => 'СССР',
                'priority' => 8,
            ],


        ];

        foreach ($events as $event) {
            HistoricalFact::updateOrCreate(
                [
                    'content' => $event['content'],
                    'event_day' => $event['event_day'],
                    'event_month' => $event['event_month'],
                ],
                array_merge($event, [
                    'is_active' => true,
                    'last_shown_at' => null,
                ])
            );
        }
    }
}
